Bottle v0.12.7 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:9900/
Hit Ctrl-C to quit.

133.9.184.16 - - [24/Nov/2015 16:15:42] "GET /svm?idf-value=2.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
133.9.184.16 - - [24/Nov/2015 16:26:35] "GET /svm?idf-value=6.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
133.9.184.16 - - [24/Nov/2015 16:37:51] "GET /svm?idf-value=1.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
133.9.184.16 - - [24/Nov/2015 16:37:51] "GET /svm?idf-value=1.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
115.162.90.178 - - [24/Nov/2015 19:30:41] "GET /svm?idf-value=6.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
Bottle v0.12.7 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:9900/
Hit Ctrl-C to quit.

66.249.85.179 - - [24/Nov/2015 23:58:42] "GET /favicon.ico HTTP/1.1" 404 758
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
66.249.85.179 - - [25/Nov/2015 22:45:38] "GET /favicon.ico HTTP/1.1" 404 758
66.249.85.131 - - [26/Nov/2015 15:38:16] "GET /svm?idf-value=5.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
66.249.85.131 - - [26/Nov/2015 15:38:17] "GET /favicon.ico HTTP/1.1" 404 758
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "api_svm.py", line 25, in svm
    idf = float(idf)
ValueError: invalid literal for float(): 6）のidf-valueに変数を組み込んで
133.30.112.156 - - [26/Nov/2015 18:06:40] "GET /svm?idf-value=6.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6%EF%BC%89%E3%81%AEidf-value%E3%81%AB%E5%A4%89%E6%95%B0%E3%82%92%E7%B5%84%E3%81%BF%E8%BE%BC%E3%82%93%E3%81%A7 HTTP/1.1" 500 1676
133.30.112.156 - - [26/Nov/2015 18:06:41] "GET /favicon.ico HTTP/1.1" 404 758
Bottle v0.12.7 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:9900/
Hit Ctrl-C to quit.

115.162.90.178 - - [26/Nov/2015 21:32:21] "GET /svm?idf-value=3.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
115.162.90.178 - - [26/Nov/2015 21:32:21] "GET /svm?idf-value=6.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
115.162.90.178 - - [26/Nov/2015 21:32:21] "GET /favicon.ico HTTP/1.1" 404 758
115.162.90.178 - - [26/Nov/2015 21:32:29] "GET /svm?idf-value=1.25&known-list=1,3.5,4&unknown-list=4,2,6,8,6 HTTP/1.1" 200 1
